import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Humanidad101",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}<script src="https://kit.fontawesome.com/3d8f845060.js" crossorigin="anonymous"></script></body>
    </html>
  );
}
